//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Address
{
    public Address()
    {
        this.BusinessEntityAddresses = new HashSet<BusinessEntityAddress>();
    }

    public int AddressID { get; set; }
    public string AddressLine1 { get; set; }
    public string AddressLine2 { get; set; }
    public string City { get; set; }
    public int StateProvinceID { get; set; }
    public string PostalCode { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual StateProvince StateProvince { get; set; }
    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; }
}

public partial class AddressType
{
    public AddressType()
    {
        this.BusinessEntityAddresses = new HashSet<BusinessEntityAddress>();
    }

    public int AddressTypeID { get; set; }
    public string Name { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; }
}

public partial class BusinessEntity
{
    public BusinessEntity()
    {
        this.BusinessEntityAddresses = new HashSet<BusinessEntityAddress>();
        this.BusinessEntityContacts = new HashSet<BusinessEntityContact>();
    }

    public int BusinessEntityID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; }
    public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }
    public virtual Person Person { get; set; }
}

public partial class BusinessEntityAddress
{
    public int BusinessEntityID { get; set; }
    public int AddressID { get; set; }
    public int AddressTypeID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Address Address { get; set; }
    public virtual AddressType AddressType { get; set; }
    public virtual BusinessEntity BusinessEntity { get; set; }
}

public partial class BusinessEntityContact
{
    public int BusinessEntityID { get; set; }
    public int PersonID { get; set; }
    public int ContactTypeID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual BusinessEntity BusinessEntity { get; set; }
    public virtual ContactType ContactType { get; set; }
    public virtual Person Person { get; set; }
}

public partial class ContactType
{
    public ContactType()
    {
        this.BusinessEntityContacts = new HashSet<BusinessEntityContact>();
    }

    public int ContactTypeID { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }
}

public partial class CountryRegion
{
    public CountryRegion()
    {
        this.StateProvinces = new HashSet<StateProvince>();
    }

    public string CountryRegionCode { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual ICollection<StateProvince> StateProvinces { get; set; }
}

public partial class EmailAddress
{
    public int BusinessEntityID { get; set; }
    public int EmailAddressID { get; set; }
    public string EmailAddress1 { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
}

public partial class Password
{
    public int BusinessEntityID { get; set; }
    public string PasswordHash { get; set; }
    public string PasswordSalt { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
}

public partial class Person
{
    public Person()
    {
        this.BusinessEntityContacts = new HashSet<BusinessEntityContact>();
        this.EmailAddresses = new HashSet<EmailAddress>();
        this.PersonPhones = new HashSet<PersonPhone>();
    }

    public int BusinessEntityID { get; set; }
    public string PersonType { get; set; }
    public bool NameStyle { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
    public string Suffix { get; set; }
    public int EmailPromotion { get; set; }
    public string AdditionalContactInfo { get; set; }
    public string Demographics { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual BusinessEntity BusinessEntity { get; set; }
    public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }
    public virtual ICollection<EmailAddress> EmailAddresses { get; set; }
    public virtual Password Password { get; set; }
    public virtual ICollection<PersonPhone> PersonPhones { get; set; }
}

public partial class PersonPhone
{
    public int BusinessEntityID { get; set; }
    public string PhoneNumber { get; set; }
    public int PhoneNumberTypeID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
    public virtual PhoneNumberType PhoneNumberType { get; set; }
}

public partial class PhoneNumberType
{
    public PhoneNumberType()
    {
        this.PersonPhones = new HashSet<PersonPhone>();
    }

    public int PhoneNumberTypeID { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual ICollection<PersonPhone> PersonPhones { get; set; }
}

public partial class StateProvince
{
    public StateProvince()
    {
        this.Addresses = new HashSet<Address>();
    }

    public int StateProvinceID { get; set; }
    public string StateProvinceCode { get; set; }
    public string CountryRegionCode { get; set; }
    public bool IsOnlyStateProvinceFlag { get; set; }
    public string Name { get; set; }
    public int TerritoryID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual ICollection<Address> Addresses { get; set; }
    public virtual CountryRegion CountryRegion { get; set; }
}
